In [ ]:
# Business Context:
# Data analyst at a B2C subscription company (telecom/SaaS/insurance). 
# Marketing spent $2M on acquisition last quarter, but churn rate is 25%. 
# Leadership asks "Why are customers leaving and how do we fix it?"

# Business Problem: 
# Company: Telecom provider with 7,043 customers
# Issue: 25% annual churn rate
# Cost: Acquiring new customer = $500, Retaining = $50
# Leadership Question: "What drives churn and how do we reduce it?"

# Key Questions:
# 1. What customer segments have highest churn risk?
# 2. What behaviors predict churn?
# 3. What interventions could reduce churn (e.g. by 5%)?
# 4. What's the ROI of retention campaigns?

# Hypotheses to Test: 
# H1. Customers with high monthly charges are more likely to churn.
# H2. Customers with month-to-month contracts have higher churn rates.
# H3. Long-term customers (over 2 years) have lower churn rates.
# H4. Customers using multiple services (internet, phone, TV) are less likely to churn. 
# H5. Customers without tech support are more likely to churn.

In [9]:
# 2. Setup ----

# Import Libraries
import pandas as pd
import numpy as np

# Settings
pd.set_option('display.max_columns', None)

# Load Data
df = pd.read_csv('telco_customer_churn.csv')
# df.head()
df.describe()
# df.columns

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [4]:
# 3. Data Cleaning ----

# Missing values

# Errroneous values